apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: microservices-secrets
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: microservices-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: microservices
        property: jwt_secret