name: elaview-backend

services:
  elaview-backend-postgres:
    container_name: elaview-backend-postgres
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_USER}
    networks: [ elaview-backend ]
    ports: [ "${DATABASE_PORT}:${DATABASE_PORT}" ]
    volumes:
      - type: volume
        source: elaview-postgres-data
        target: /var/lib/postgresql

networks:
  elaview-backend:
    name: ${DATABASE_USER}

volumes:
  elaview-postgres-data:

