name: elaview-backend

services:
  database:
    container_name: elaview-backend-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${ELAVIEW_BACKEND_DATABASE_USER}
      POSTGRES_PASSWORD: ${ELAVIEW_BACKEND_DATABASE_PASSWORD}
      POSTGRES_DB: ${ELAVIEW_BACKEND_DATABASE_USER}
    networks: [ elaview-backend ]
    ports: [ "${ELAVIEW_BACKEND_DATABASE_PORT}:${ELAVIEW_BACKEND_DATABASE_PORT}" ]
    volumes:
      - type: volume
        source: elaview-postgres-data
        target: /var/lib/postgresql
  
  server:
    container_name: elaview-backend-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ELAVIEW_BACKEND_ASPNETCORE_ENVIRONMENT: ${ELAVIEW_BACKEND_ASPDOTNETCORE_ENVIRONMENT}
      ELAVIEW_BACKEND_DATABASE_HOST: elaview-backend-postgres
      ELAVIEW_BACKEND_DATABASE_PORT: ${ELAVIEW_BACKEND_DATABASE_PORT}
      ELAVIEW_BACKEND_DATABASE_USER: ${ELAVIEW_BACKEND_DATABASE_USER}
      ELAVIEW_BACKEND_DATABASE_PASSWORD: ${ELAVIEW_BACKEND_DATABASE_PASSWORD}
      ELAVIEW_BACKEND_SERVER_PORT: ${ELAVIEW_BACKEND_SERVER_PORT}
      ELAVIEW_BACKEND_SERVER_TLS_CERT_PATH: ${ELAVIEW_BACKEND_SERVER_TLS_CERT_PATH}
      ELAVIEW_BACKEND_SERVER_TLS_CERT_PASSWORD: ${ELAVIEW_BACKEND_SERVER_TLS_CERT_PASSWORD}
      ELAVIEW_BACKEND_AUTH_COOKIE_NAME: ${ELAVIEW_BACKEND_AUTH_COOKIE_NAME}
      ELAVIEW_BACKEND_CORS_ORIGINS: ${ELAVIEW_BACKEND_CORS_ORIGINS}
    networks: [ elaview-backend ]
    ports:
      - "${ELAVIEW_BACKEND_SERVER_PORT}:${ELAVIEW_BACKEND_SERVER_PORT}/tcp"
      - "${ELAVIEW_BACKEND_SERVER_PORT}:${ELAVIEW_BACKEND_SERVER_PORT}/udp"
    volumes:
      - type: bind
        source: ./TLS
        target: /app/TLS
        read_only: true
      - type: volume
        source: elaview-dataprotection-keys
        target: /root/.aspnet/DataProtection-Keys
    depends_on:
      - database

networks:
  elaview-backend:
    name: ${ELAVIEW_BACKEND_DATABASE_USER}

volumes:
  elaview-postgres-data:
  elaview-dataprotection-keys:
