name: Validate

on:
  pull_request:
    branches: [ experimental/ci-cd ]

concurrency:
  group: validate-${{ github.ref }}
  cancel-in-progress: true

env:
  ELAVIEW_ENVIRONMENT: development
  DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}

jobs:
  validate-web:
    name: Validate Web
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: devbox run -- bash -e {0}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: true

      - name: Install
        run: ev web:install

      - name: Lint
        run: ev web:lint

      - name: Typecheck
        run: ev web:typecheck

      - name: Test
        run: ev web:coverage

      - name: Build
        run: ev web:build

  validate-backend:
    name: Validate Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: devbox run -- bash -e {0}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: true

      - name: Restore
        run: ev backend:install

      - name: Lint
        run: ev backend:lint

      - name: Build
        run: ev backend:build

      - name: Test
        run: ev backend:test
